[package]
name = "maci-crypto-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "example"
crate-type = ["staticlib"]

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
